@echo off

set PRIORI_DATABASE_PORT=1433
set PRIORI_DATABASE_NAME=Priori
set PRIORI_DATABASE_USER=sa
set PRIORI_DATABASE_IP=192.168.0.93
set PRIORI_DATABASE_PASSWORD=root
set PRIORI_SECRET_JWT_KEY=

dotnet watch